### ISSUE TITLE
The "['foo.js', 'bar.js']" loading order seems to be left-side right 

### ISSUE THREAD

**Issue by ArthurMaps** [muicss/loadjs#1]
The "['foo.js', 'bar.js']" loading order seems to be left-side right 
--------------
I only tested on chrome
['1.js', '2.js']
on chrome the loading order is  2.js --> 1.js
Is that a bug ?

**Comment by amorey** [comment]
The &lt;script&gt; elements are added to the DOM right to left due to this speed optimization here:
https://github.com/muicss/loadjs/blob/master/src/loadjs.js#L122

However, since all scripts are loaded in "async" mode the browser will download the files in parallel and execute them in which ever order they arrive (i.e. not the order they were added to the DOM).

If you want to guarantee that files are fetched in order you can use LoadJS callbacks:

```javascript
loadjs('1.js', function() {
  loadjs('2.js', function() {
    // 1.js loaded then 2.js loaded
  });
});
```

I've added an example to show how to load files in series to the README (https://github.com/muicss/loadjs).

Hope that helps! Let me know if you have any questions/suggestions.

**Comment by ArthurMaps** [comment]
I'm not very clear about this:
```javascript
// load multiple files (in series)
loadjs('foo.js', function() {
  loadjs('bar.js', function() {
    // foo.js loaded then bar.js loaded
  });
});
```
This seems like not download in parallel , each file interval about 10-15ms

I want that all js files download in parallel , and execute by the order I added them.
Yeah , like the ```<script src='x.js' defer='defer'> ```, just additionally support the Inline JS code

Nowadays most browser always download 10 or more js,css,image files at the same time
so can two lines of " loadjs('riot.min.js') " always down in parallel and don't have to use ['1.js' , '2.js'] ?

Thanks for you reply very much , much to my regret , I'm just a green hands

**Comment by amorey** [comment]
If you don't mind loading files before the window "load" event fires (i.e. when the browser has finished rendering) then you can use vanilla HTML to download files in parallel and execute them in order:

```html
<html>
  <head>
    <script src="1.js"></script>
    <script src="2.js"></script>
  </head>
</html>
```

If you want to fetch a file after the browser has finished rendering then you can use LoadJS. Here's an example of how to use LoadJS in conjunction with the vanilla HTML above:

```html
<html>
  <head>
    <script>/* inline source of LoadJS here */</script>
    <script src="1.js"></script>
    <script src="2.js"></script>
    <script>
      loadjs('/analytics.js', function() {
        // analytics.js loaded after window "load" event
      });
    </script>
  </head>
</html>
```

While it's technically possible to load files in parallel and execute them in order after the window "load" event, it will introduce some complexity to your code and it's beyond the scope of LoadJS. Here's a good article that explains all the intricacies of script loading:

http://www.html5rocks.com/en/tutorials/speed/script-loading/

The two methods you can use to accomplish your goal are async="false" and using XHR/eval().

**Comment by amorey** [comment]
@ArthurMaps Let me know what you think about this feature proposal: https://github.com/muicss/loadjs/issues/4
