### ISSUE TITLE
Why scripts are removed after the loading?

### ISSUE THREAD

**Issue by revyh** [muicss/loadjs#10]
I have no problem with [that](https://github.com/muicss/loadjs/blob/e22de36c39a599ea20162a03144be86556334b1a/src/loadjs.js#L84-L89). Just wondering. It's looking weird.

**Comment by amorey** [comment]
This line originally came from jQuery's ajax loading code:
https://github.com/jquery/jquery/blob/239169bb2ede6ea6287d82d1d13b0c354f451749/src/ajax/script.js#L55

**Comment by revyh** [comment]
Thanks for the clarification. For me `$.getScript` more like remote-procedure-call, than script loader. I scanned history of mentioned jQuery file and it looks like this code has been there since the beginning of jQuery existence on github (2011). I dunno, maybe this code came from an earlier IE6 era and now doesn't make sense and can be safely deleted. Anyway, remove it or leave alone - you decide. I don't insist that this is a bug.

**Comment by amorey** [comment]
That makes sense... let me think about it some more but I'm leaning towards removing the code as well. Can you think of any benefits to keeping the behavior the same?

**Comment by revyh** [comment]
Well, I think we can use this behavior to handle errors. When loading errors occur, we can call a callback function and remove a failed script by default. I do not know in what order it should be, and whether we should give users the ability to prevent script removal. Maybe it would be better to make a simple removal right now, and if someone wants to have more control in the future, then the appropriate option can be added.

**Comment by amorey** [comment]
@revyh After some thought, I think it makes sense to keep the `<script>` tags in the DOM. LoadJS is different than `$.getScript` and is used to load js libraries, not to execute remote procedure calls. The code has been removed in the latest version of loadjs (v1.0.2).

Let me know if your run into any issues or if you have any more thoughts on the subject.

**Comment by revyh** [comment]
Thanks! I just updated and everything looks good.
