### ISSUE TITLE
Is it possible to load JSON?

### ISSUE THREAD

**Issue by migliori** [muicss/loadjs#101]
Hi,

I can't figure out how to load a JSON file and access the JSON object, is it possible?
Perhaps it would be interesting to be able to code something like this?:

```
loadjs(['json!/path/to/file.json'], function(obj) {
    /* file.json loaded as json */
    console.log(obj);
});
```

**Comment by amorey** [comment]
LoadJS uses the browser's built-in tags (`<script>`, `<style>`, `<img>`) to load files and as far I know you can't load JSON directly using those tags. However, you can use the [jsonp method](https://www.w3schools.com/js/js_json_jsonp.asp) in conjunction with LoadJS if that's useful:

Client code:

```javascript
window.callbackFn = function(json) {
  console.log(json);
}

loadjs('/server-endpoint', function() {
  // server has responded and callbackFn has been called
});
```

Server reponse:
```javascript
callbackFn({
  mykey1: myval1,
  mykey2: myval2,
  ...
});
```

**Comment by migliori** [comment]
Thanks for your answer, in most cases it would be a good solution
(unfortunately not for me, I'm inside a tinyMce plugin dialog iFrame with TypeScript, so I'll use XMLHttpRequest instead)
