### ISSUE TITLE
Using loadjs in a Vanilla project: require is not defined error

### ISSUE THREAD

**Issue by MartijnHarmenzon** [muicss/loadjs#104]
I'm running a Vanilla JS project without any builders or frameworks. I would like to make use of loadjs but I'm getting the error: 

> require is not defined

My code:
```
  <script src="https://unpkg.com/loadjs@4.2.0/dist/loadjs.min.js"></script>
  <script>const loadjs = require('loadjs');</script>
```

How to include loadjs in a Vanilla project?

**Comment by amorey** [comment]
Since you're using the standalone browser payload, the loadjs library is available via the `loadjs` global:

```html
<script src="https://unpkg.com/loadjs@4.2.0/dist/loadjs.min.js"></script>
<script>
  loadjs(["/path/to/foo.js", "/path/to/bar.js"], function() {
    /* foo.js and bar.js loaded */
  });
</script>
```

Hope that helps! I updated the README to make this clearer.

**Comment by MartijnHarmenzon** [comment]
@amorey Thanks for the reply. It works. Close #104
