### ISSUE TITLE
Old browsers (Opera12) can't use document.head

### ISSUE THREAD

**Issue by viT-1** [muicss/loadjs#107]
Your code failed on `doc.head.appendChild`
It should be `doc.querySelector('head').appendChild`

**Comment by amorey** [comment]
On which version of Opera12 did you see an error and what is the error message? I just tested the following code on Opera 12.15 and it works:

```html
<!doctype html>
<html>
  <head>
    <title>Opera12 Test</title>
  </head>
  <body>
    <script>
      (function (doc) {
        var el = doc.createElement('script');
        el.src = 'doesntexist.js';
        doc.head.appendChild(el);
      })(document);
    </script>
  </body>
</html>
```

**Comment by viT-1** [comment]
Strange... This failed only if Developer tools is already open.

**Comment by amorey** [comment]
Hmm... maybe developer tools has a setting enabled that's changing the default behavior. Have you noticed the error in a context that affects users? Can I close this issue?
