### ISSUE TITLE
load scripts in order without nesting?

### ISSUE THREAD

**Issue by pateketrueke** [muicss/loadjs#2]
Is this possible?

```javascript
loadjs.ready(['moment/moment.js', 'moment/locale/es.js'], function() {
  console.log(moment);
});
```

If both scripts are loaded in parallel there is no guarantee if `moment` is loaded before locales?

I don't like nesting callbacks, you know, aka callback-hell.

**Comment by amorey** [comment]
@pateketrueke Loading scripts in parallel and executing them in order *after* the window "load" event can have some unintended side effects. Read the comments in this issue for more details:
https://github.com/muicss/loadjs/issues/1

If you're hosting the scripts yourself, one option to consider is wrapping them in a`loadjs.ready()` call. For example, if you wrap the source code of moment/locale/es.js in ```loadjs.ready('moment', function() {})``` then this will accomplish what you want:

```javascript
loadjs('moment/moment.js', 'moment');
loadjs('moment/locale/es.js');
```

**Comment by amorey** [comment]
@pateketrueke Let me know what you think about this feature proposal for async=false: https://github.com/muicss/loadjs/issues/4
