### ISSUE TITLE
load CSS

### ISSUE THREAD

**Issue by neuropass** [muicss/loadjs#21]
Could you add the possibility of loading other common resources Asynch? Like CSS for example. would this be possible without adding too much code overhead to loadJS?

Or perhaps creating new repos and have few handy modules that can be imported to add extra optional functionality to loadJS?   

Let me know your thoughts.

**Comment by amorey** [comment]
I think adding support for CSS is a good idea. It'll add some overhead but not very much. Are there any other resources that you need?

**Comment by neuropass** [comment]
I think CSS would be perfect and probably the most used.

**Comment by amorey** [comment]
@neuropass I added support for CSS file loading in the `loadjs:css` branch:
https://github.com/muicss/loadjs/tree/css

Please try it out and let me know if you run into any issues.

**Comment by amorey** [comment]
CSS support has been added to LoadJS v2.1.0:
https://github.com/muicss/loadjs
https://www.npmjs.com/package/loadjs
