### ISSUE TITLE
Invalid bower.json

### ISSUE THREAD

**Issue by stowball** [muicss/loadjs#25]
```sh
bower loadjs#* invalid-meta The "main" field cannot contain minified files
bower loadjs#* invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["dist/loadjs.js","dist/loadjs.min.js"]
```

When you use a package like https://www.npmjs.com/package/main-bower-files, both js files then get aded to the page

**Comment by amorey** [comment]
Thanks for the bug report.  The problem has been fixed and is now live in the latest version (3.0.0). Let me know if you are still having problems using loadjs with bower.

Fixed via https://github.com/muicss/loadjs/commit/c988fb0041122d4b5dfecc3014fa4d2bd52efda5
