### ISSUE TITLE
`fail` callback is incorrectly named

### ISSUE THREAD

**Issue by stowball** [muicss/loadjs#26]
Fail is a verb, not a noun like success, so failure or error should be used.

**Comment by amorey** [comment]
Thanks for the suggestion. jQuery uses success/error too so I think users will be used to that nomenclature. I switched the callback function name from "fail" to "error" and the code is now live in the latest version (3.0.0).

Fixed via https://github.com/muicss/loadjs/commit/8703b645727cecbb0e05d8d59c6c839a17b27fa2

**Comment by stowball** [comment]
Superstar!
