### ISSUE TITLE
Feature Proposal: Single success/fail callback function

### ISSUE THREAD

**Issue by amorey** [muicss/loadjs#3]
I've been thinking about simplifying the LoadJS API by combining the success/fail callback into one function that gets passed in a list of unmet dependencies:

```javascript
loadjs(['foo.js', 'bar.js'], function(pathsNotFound) {
  if (pathsNotFound.length) return;  // at least one file failed
});
```

The advantage of merging the success/fail callbacks is that it simplifies the API and exposes script request failures in a more concise way.

Let me know if you have any thoughts or suggestions!

**Comment by amorey** [comment]
I'm leaning away from implementing a single callback because it would make nested calls more complicated.

Example using current interface:
```javascript
loadjs('foo.js', function() {
  loadjs('bar.js', function() {
    // foo.js and bar.js loaded
  }); 
});
```

Example using proposed interface:
```javascript
loadjs('foo.js', function(pathsNotFound) {
  if (pathsNotFound.length) return;

  loadjs('bar.js', function(pathsNotFound) {
    if (pathsNotFound.length) return;

    // foo.js and bar.js loaded
  }); 
});
```

Let me know if you have any thoughts!

**Comment by rarkins** [comment]
I think you can close this? The description of "current interface" is outdated anyway.

**Comment by amorey** [comment]
Yes, that makes sense. Thanks for pointing it out!
