### ISSUE TITLE
, type='text/javascript')

### ISSUE THREAD

**Issue by cekvenich** [muicss/loadjs#33]
Hi, I'm using your great loader a few places, ex: https://cekvenich.site44.com/post/IDE/.

If you view console - notice the warning that chrome will follow spec and stop loading if type='text/javascript'  and such is missing. I hope you can view the console and help decipher the warning, I think that is what they are saying. 
( source is here but you won't need it 
https://github.com/cekvenich/murder/tree/master/cekvenich.site44.com )

I have to deploy new code before. Can you please add types to all loads based on extension?
ex: .js is text/javascript' .

**Comment by amorey** [comment]
The warning in the console refers to invalid type/language attributes and as far as I know a missing `type` attribute is still considered valid (it gets set to ["text/javascript" by default](http://stackoverflow.com/questions/4195427/is-the-type-attribute-necessary-for-script-tags)). 

In your source HTML there are two tags with `type="riot/tag"`, is it possible these are causing the warning:
```html
<script src="/_compHost/home-card.tag" type="riot/tag"></script>
<script src="/_compHost/x-vid.tag" type="riot/tag"></script>
```

**Comment by cekvenich** [comment]
That was the error.
Pardon me.
