### ISSUE TITLE
Delay adding scripts

### ISSUE THREAD

**Issue by matthiasg** [muicss/loadjs#35]
I would like to load a number of scripts in parallel but delay their insertion into dom (and thus parsing/execution) until another unrelated async event has happened (SSR rendered html loading).

it this possible somehow ? I had assumed I could use the `before` handler to set the script type to something like 'dummy' until the time is right and then switch the elements type (in order) .. but that does not work it seems since success is never triggered.

Is this possible somehow ?

**Comment by amorey** [comment]
LoadJS uses `<script>` tags to load scripts which doesn't give you control over the script contents or the execution time. If you want to control the parsing/execution of your scripts, you can use XHR requests to fetch the script content and run `eval()` on the payload but this only works for requests that conform to the browser's security policy (i.e. same domain or CSP requests).

In terms of controlling the timing, you can loadjs as a simple pubsub system by taking advantage of the `loadjs.done()` method:
```javascript
loadjs.ready(['dep1', 'dep2'], {
  success: function() {
    // run code here when dep1 and dep2 are ready 
  }
});

function fn1() {
  loadjs.done('dep1');
}

function fn2() {
  loadjs.done('dep2');
}
```

**Comment by matthiasg** [comment]
@amorey this would not influence timing of execution/evaluation though or does it ? On supported browsers its easiest to add link "preload" and use loadjs when eval should happen I guess.

**Comment by amorey** [comment]
What are you referring to when you ask about influencing the timing of execution/evaluation? LoadJS uses `<script>` tags which gives you control over when to start the file fetch but not when to evaluate or execute it. To gain more control over the execution time you can implement your own loading function which uses XHR requests. The `loadjs.done()` method can be used to implement a simple dependency manager in case you want to execute your code only after some other dependencies have been met.

With regards to the "preload" attribute, it looks like it only works for `<audio>` and `<video>` elements:
http://www.w3schools.com/tags/att_preload.asp

**Comment by matthiasg** [comment]
@amorey with regards to preload I am talking about e.g `<link rel="preload" href="/dist/vendor.62d7882d70f3b9499b6a.js" as="script">` which (on supported browsers) triggers a script load without automatically evaluating it at the end. See https://developers.google.com/web/updates/2016/03/link-rel-preload.

This allows me to trigger downloading some scripts and e.g data/html in parallel, but delay parsing and evaluating, Once my html/data is loaded (e.g via XHR/fetch) I can then add the appropriate script tags to the document which would execute as before, but make use of either already pre-loaded scripts or wait until their completion before parsing and evaluating it in the order I specify. XHR can also do this with more work since CORS and other headers have to be set correctly.

Before link rel="preload" another alternative was to use a wrong type attribute for the script tag which would also delay eval, but had some undesirable consequences (server mime type headers etc).

I solved my issue by adding preload link tags manually, then waiting for my data/html to come in, and then call loadjs to finish up (or I could have added the tags myself of course).
