### ISSUE TITLE
Dedupe script paths and/or how to inspect in-flight requests?

### ISSUE THREAD

**Issue by akrawchyk** [muicss/loadjs#38]
I'm using loadjs to async load the Select2 jQuery plugin (https://select2.github.io/) that I use for 2 different use cases: 1) search autocomplete 2) location suggestions. The location suggestions depends on another data adapter, but both cases need the same plugin files other than that:

```
loadjs([
  '/js/select2.js',
   '/css/select2-theme.css'
], 'select2', {
   success: initKeywordAutocomplete
});

loadjs([
  '/js/select2.js',
  '/js/select2-places.js',
  '/css/select2-theme.css'
], 'select2-places', {
  async: false,  // load in series to ensure select2 is available before the places data adapter
  success: initLocationAutocomplete
});
```

If I use the above code on a page, `select2.js`, `select2-theme.css` will both be added to the DOM twice, and `select2-places.js` will only be added once.

First, is it reasonable to add an enhancement to loadjs that dedupes the scripts added to the DOM? Currently only bundles are deduped by their id's, but I'm thinking of saving the script paths too so they aren't appended to the DOM more than once.

Second, I can see why it would be a bad idea to expose the bundle dependency tracker objects, and instead have the `.reset()` function to let users clear them out. But, is there a way to inspect the requests loadjs has initiated? Or should I just query the DOM for a script tag for the `src` I want to avoid downloading twice?

Thanks in advance!

**Comment by akrawchyk** [comment]
P.S. -  what I'd _really_ like to be able to do is use bundle id's in the paths array, like the following:

```
loadjs([
  '/js/select2.js',
   '/css/select2-theme.css'
], 'select2', {
   success: initKeywordAutocomplete
});

loadjs([
  'select2',
  '/js/select2-places.js',
], 'select2-places', {
  async: false,  // load in series to ensure select2 is available before the places data adapter
  success: initLocationAutocomplete
});
```

**Comment by amorey** [comment]
Hi @akrawchyk!

You can use the `.ready()` method to use bundle ids as dependencies. For example, you can load `select2.js` and `select2-places.js` sequentially like this:

```javascript
loadjs(['/js/select2.js', '/css/select2-theme.css'], 'select2', {
  success: initKeywordAutocomplete
});

loadjs.ready(['select2', 'select2-places'], {
  success: function() {
    loadjs('/js/select2-places.js', {
      success: initLocationAutocomplete
    });
  }
});
```

If you want to load `select2.js` and `select2-places.js` in parallel and execute them in series this should work:
```javascript
loadjs(['/js/select2.js', '/css/select2-theme.css'], 'select2', {
  success: initKeywordAutocomplete
});

loadjs('/js/select2-places.js', 'select2-places', {async: false});

loadjs.ready(['select2', 'select2-places'], {
  success: initLocationAutocomplete
});
```

However, given my understanding of the problem I think I would just load all the files with `async: false` and run both init methods after load:
```javascript
loadjs([
  '/js/select2.js',
  '/js/select2-places.js',
  '/css/select2-theme.css'
  ],
  {
    async: false,
    success: function() {
      initLocationAutocomplete();
      initKeywordAutocomplete();
    }
  }
);
```

Hope that helps!

**Comment by akrawchyk** [comment]
@amorey thanks for the speedy response and the helpful examples!

I've been tinkering with this and was overlooking the `ready` function, I appreciate you pointing it out. This works well for a single script, and I have updated my code.

I might be spinning my wheels here, but what about detecting bundle loads across modules. For example, if 2 distinct modules that may or may not be loaded on the same page depend on select2:

```
<script>
    loadjs([
        window.__STATIC__['js/select2.js'],
        window.__STATIC__['css/select2-theme.css']
    ], 'select2');
</script>
<script>
    try {
        loadjs([
            window.__STATIC__['js/select2.js'],
            window.__STATIC__['css/select2-theme.css']
        ], 'select2');
    } catch (e) {
        // another module registered loading select2
    }
</script>
```

Is it possible to detect select2 being previously loaded without using try/catch or a global variable I set myself? If I were to assign a different bundle id to each loadjs call, the scripts would be added to the DOM twice...

**Comment by amorey** [comment]
Currently it's not possible to inspect `LoadJS`'s internal bundle cache without using `try/except` as in your example. Would exposing the bundle ids via a dictionary work for you?
```html
<script>
  if (!loadjs.bundleIds['my-bundle']) {
    loadjs(['1.js', '2.js'], 'my-bundle');
  }
</script>
```

**Comment by akrawchyk** [comment]
@amorey that would be all I would need, but that does expose the id's to be modified externally. Changing or removing them could lead to unexpected behavior. Your call on what's best for loadjs! 😄

**Comment by amorey** [comment]
Hi @akrawchyk - sorry for the late response. I have a working version with an `isDefined()` method:

```javascript
<script>
  if (!loadjs.isDefined('my-bundle')) {
    loadjs(['1.js', '2.js'], 'my-bundle');
  }
</script>
```

Let me know if this would solve your problem and if you have any suggestions for the method name and syntax.

**Comment by amorey** [comment]
@akrawchyk I just wanted to check in. Do you have any thoughts on the `isDefined()` method?

**Comment by akrawchyk** [comment]
@amorey this looks great! I think it's a good idea to avoid exposing the bundle registry as an object, so having an `isDefined` API method makes sense to me 👍

**Comment by akrawchyk** [comment]
Literally just thought of this as soon as I pressed "Comment"...

When are you thinking the call to `isDefined` would return `true` for a bundle? After it's initially registered, or after it's been loaded? I'd think returning `true` after a bundle is registered is a must, otherwise the same bundle could be registered twice while we wait for the bundle to load.

**Comment by amorey** [comment]
Thanks for the feedback! It would return `true` after the bundle is registered. The `.ready()` method can be used to execute a callback after the dependencies have been loaded.

**Comment by amorey** [comment]
Done! The added an `isDefined()` method to v3.4.0 and updated the code on github/npm. Let me know if you run into any problems using the new method.
