### ISSUE TITLE
Feature Proposal: Async=false option for parallel loading, synchronized execution

### ISSUE THREAD

**Issue by amorey** [muicss/loadjs#4]
A few users have requested the ability to load files in parallel and execute them in order. By default, LoadJS requests are asynchronous but by setting the async attribute to false on &lt;script&gt; we can enable the desired behavior.

To accommodate async=false behavior, I propose we add support for an optional argument to `loadjs`:

```javascript
// load files in parallel and execute them in order
loadjs(['foo.js', 'bar.js'], function() { }, {async: false});
```

Let me know what you think!

**Comment by pateketrueke** [comment]
+1

**Comment by amorey** [comment]
@pateketrueke Thanks for the feedback! Any thoughts on this proposal: https://github.com/muicss/loadjs/issues/3

**Comment by amorey** [comment]
I have a working version of LoadJS with async=false in the `async-false` branch but the tests are failing in Chrome and IE when fetching a file that returns an HTTP 404. The LoadJS callbacks are executing after the Mocha test callback which causes Mocha to report an error. This is the test that's failing:
https://github.com/muicss/loadjs/blob/async-false/test/tests.js#L86

The internet has a fair number of warnings against using async=false so I think we should stay away from this feature for now. If anyone wants to look deeper into the issue they are encouraged to try!

**Comment by taoeffect** [comment]
In case you find this helpful thought I'd mention this link: http://www.html5rocks.com/en/tutorials/speed/script-loading/

**Comment by amorey** [comment]
Thanks! Would you be interested in working on a version of `loadjs` that adds `async=false`?

**Comment by taoeffect** [comment]
@amorey To support dynamic injection of inlined scripts (i.e. of the `<script type="text/javascript"> /* code */ </script>`) I think I'll take a different approach, which is to serialize them in the order they appear in the template using a "global" (to the library) Promise object.

**Comment by amorey** [comment]
Interesting - I'm curious to see if that works. Let me know if you want some feedback.

**Comment by pateketrueke** [comment]
+1

**Comment by taoeffect** [comment]
Cool. Well then, I just published my little library that does just that. Feel free to check it out and play with it: [`vue-router2`](https://github.com/taoeffect/vue-script2)

**Comment by taoeffect** [comment]
VueScript2 now does [promise-based imperative loading](https://github.com/taoeffect/vue-script2/blob/master/README.md#promise-based-imperative-loading-too) as well.

**Comment by rarkins** [comment]
@amorey wasn't this implemented already?

**Comment by amorey** [comment]
Yes, it's accessed via the `async:false` option:

```javascript
loadjs(['/path/to/foo.js', '/path/to/bar.js'], {
  success: function() { /* foo.js and bar.js loaded in series */ },
  async: false
});
```

Thanks for pointing it out. I'll close this issue.
