### ISSUE TITLE
Able to get js to work, but not css.

### ISSUE THREAD

**Issue by KerryRuddock** [muicss/loadjs#43]
As more people discover [page insights](https://developers.google.com/speed/pagespeed/insights/) they will be coming here to resolve render-blocking js and css and this is the reason why I am trying out your software.  I tried implementing load.js on my javascript which worked great, but then I added links to my css in 1st two lines of loadjs and my website is now unstylized.  Here is how I am using your loadjs software in my <head> section:
`  <-- <script>
    window.addEventListener('load', function() {
      loadjs(["https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css",
              "styles/style.css",
  	      "https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.min.js",
              "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js",
              "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js",
              "scripts/djmarketing.js"], {
        success: function djMain() { /* loaded in series */ },
        async: false
      });
    });
  </script> -->`

**Comment by amorey** [comment]
What problems are you running into? Here's a JSFiddle example based on your code snippet (but without the  `window.addEventListener` call):
https://jsfiddle.net/muicss/13w43zbx/2/

The example loads the Bootstrap CSS file successfully but can't find `styles/style.css` which is expected.

**Comment by KerryRuddock** [comment]
Hi Amorey,

Thanks for getting back to me.  It was human error as I  had script loadjs.min.js commented out ( silly me - i was running DomContentLoaded tests with and without loadjs and forgot! ) that caused the problem.  So now loadjs is loading my css/js, but I don't understand why page insights still thinks I have render-blocking css?  Prior to discovering loadjs, I had render blocking javascript and so I know your script resolved the render blocking issues for javascript, but not for css as I was hoping it would.

**Comment by amorey** [comment]
Are you loading the CSS after the window `load` event fires? If so, that would explain the FOUT.

**Comment by KerryRuddock** [comment]
I am loading the css just the way I posted it here in the <head> section.
What am I missing?

**Comment by amorey** [comment]
The browser will render the page (and then fire the window `load` event) after all the HTML, CSS, images and scripts that are in the DOM at that point have been loaded. If you load CSS after the widow `load` event fires then that it will cause FOUT if it modifies the style of an element that is visible on the page.

Personally, I would recommend using plain old `<link rel="stylesheet">` tags in the `<head>` for CSS that is required on pageload. To optimize pageload times you can serve static files from a CDN gzipped with the appropriate cache headers set.

**Comment by KerryRuddock** [comment]
I appreciate your feedback, so I am missing the interpretation of how loadjs works?  I thought the window load event would not fire until loadjs completely processed all css and js passed to it?

**Comment by amorey** [comment]
`loadjs` adds elements to the DOM immediately so if you use it before window `load` then the browser will delay the firing of that event until those files have finished downloading as well.

I just ran some tests and confirmed that this is the behavior of `loadjs` but it appears that Chrome will sometimes display FOUT when a CSS file is loaded dynamically even if the file is loaded before the window `load` event fires. I'm not sure how to prevent this any than loading CSS files the old fashioned way.

**Comment by amorey** [comment]
@KerryRuddock Any updates on the FOUT issue?

**Comment by KerryRuddock** [comment]
Thanks Amorey for a follow up.  Just to recap where we left off.
- I am trying to speed up my website after testing my site at [page insights](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fkerryruddocktesthosting-com.stackstaging.com%2Fbootstrap%2Fdjmarketing%2Findex.html) 
- loadjs helped resolve render-blocking javascript, but unfortunately but caused the FOUT issue.

The workaround I am using came from this [article](https://www.appneta.com/blog/bootstrap-pagespeed/) and viewing his source on github which showed me that I could dynamically insert the bootstrap.min.css and then inline my own css afterwards seems to have resolved the FOUT.

.IE
```
 <script>
  var cb = function() {
    var l = document.createElement('link'); l.rel = 'stylesheet';
    l.href = 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css';
    var h = document.getElementsByTagName('head')[0]; h.parentNode.insertBefore(l, h);
  };
  var raf = requestAnimationFrame || mozRequestAnimationFrame ||
  webkitRequestAnimationFrame || msRequestAnimationFrame;
  if (raf) raf(cb);
  else window.addEventListener('load', cb);
  </script>
```

I am closing this issue.  Thank you for your help.

**Comment by amorey** [comment]
Great, thanks for the follow up. That's actually what `loadjs` does under the hood (with the added benefit of success/error callbacks and simple dependency management) so this is the equivalent with `loadjs`:
```html
<script>
  var cb = function() {
    loadjs('//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css');
  };

  var raf = requestAnimationFrame || mozRequestAnimationFrame || webkitRequestAnimationFrame || msRequestAnimationFrame;
  if (raf) raf(cb);
  else window.addEventListener('load', cb);
</script>
```

**Comment by KerryRuddock** [comment]
Oh I did have it that way originally, but my page speed scores were not great due to render blocking.  I wish there was a way to private message you directly so that I could give you my web site linkages showing to demonstrate page speed scores before and after

**Comment by amorey** [comment]
Surem you can reach me here: contact@muicss.com
