### ISSUE TITLE
unload?

### ISSUE THREAD

**Issue by puppetmaster3** [muicss/loadjs#45]
How can I unload?

One way: load to a div w/ id and then remove div. Is that good or is there a better way?
Require does this: http://stackoverflow.com/questions/11899967/require-js-remove-definition-to-force-reload/18521604#18521604

**Comment by amorey** [comment]
What do you mean by unload? You can delete a `<script>` from the DOM but the JavaScript code will still be available.

**Comment by puppetmaster3** [comment]
I found a way to listen (via event steam)
