### ISSUE TITLE
Retry after some time instead of immediatly

### ISSUE THREAD

**Issue by tareco** [muicss/loadjs#49]
Hi,

Is it possible to retry the load after some time? The use-case is for a resillient application (not a web-site) that needs to wait until a file becomes available. In this case I set the number of retries very high and would like to try the load every few seconds instead of immediatly, which hammers the server.

Thanks

**Comment by amorey** [comment]
Currently there's no built-in way to add a retry delay but you should be able to set up a function that uses the success/failure callbacks to implement your own retry strategy. I'd be curious to see how you implement this so we can think about adding it to the core library (though, I'm definitely biased towards a minimalist feature set).

**Comment by tareco** [comment]
I'm not sure how to implement it, but I can give it a try if you help me out with some rough ideas.
Using callbacks how do I make sure the next file will wait for the retries?
The sequence is done by this for I believe:
for (i=0; i < x; i++) loadFile(paths[i], fn, args);
But if intercept the for with callbacks, the files will not load in sequence anymore.

**Comment by amorey** [comment]
Combining retries with parallel fetch + sequential load is going to be very tricky. In fact I'm not sure if you can even do it in a cross-browser way right now (`rel="preload"` should allow this in the future).

Using LoadJS with the retry feature, you can fetch multiple files in parallel and use the `success` callback to execute a function after they have all been loaded (and executed) by the browser:

```javascript
loadjs['/path/to/foo.js', '/path/to/bar.js'], 'foobar', {
  success: function() { /* foo.js & bar.js loaded */ },
  numRetries: 3
});
```

In this example, LoadJS will add `foo.js` to the DOM first but if `bar.js` arrives first or if `foo.js` triggers a retry, then `bar.js` will be loaded/executed first.

**Comment by tareco** [comment]
I understand what you are saying, but for my case, since I don't need the parallel fetch, this would be perfect:
```
// exit function and try again
if (numTries < maxTries) {
  sleep(1000); // <--- I think this only what I need
  return loadFile(path, callbackFn, args, numTries);
}
```

**Comment by tareco** [comment]
But better would be to implement this:
```
loadjs['/path/to/foo.js', '/path/to/bar.js'], 'foobar', {
  success: function() { /* foo.js & bar.js loaded */ },
  numRetries: 3,
  retryDelay: 1000
});
```

**Comment by amorey** [comment]
Javascript doesn't have a `sleep()` function. For delayed execution you need to use `setTimeout()` to asynchronously execute a callback after an amount of time has passed.

Unfortunately, loading external javascript files in series is actually trickier than loading them in parallel. Currently, there are only two cross-browser ways to load/execute external javascript files in series:

  1. By using embedded `<script>` tags in the page source (in the order you want the files loaded/executed)
  2. By setting `async="false"` to dynamically added `<script>` tags

LoadJS uses the second method when you use the `async: false` option. Although this works well if there's no download failure, if you have to retry a download then it will get added to the DOM out of order which is problematic if you need the files to execute in series.

In general, the browser (and Javascript) prefer parallel, asynchronous execution so to keep things simple I would write your code so that the files can be loaded asynchronously. LoadJS can help in a few ways, including by allowing you to execute an init method after the dependencies have been met:

```html
<script>
  loadjs(['/path/to/foo.js', '/path/to/bar.js'], {
    success: function() {
      initFoo();
      initBar();
    },
    numRetries: 3
  });
</script>
```

**Comment by tareco** [comment]
Thank you for your explanations.
I can live with parallel loading, I just need to adjust a few things.
What I can't risk is the server being hammered while a file is missing in the server...
I'd really love a solution for that, but so far I found none.

**Comment by amorey** [comment]
If you want a quick prototype this should work:
```html
<script>
  function loadFile(url, delayMsec, callbackFn) {
    loadjs([url], {
      success: callbackFn
      error: function() {
        setTimeout(function() {loadFile(url, delayMsec, callbackFn);}, delayMsec);
      }
    });
  }

  loadFile('/path/to/foo.js');
</script>
```

Are you trying to load static files? If so, it might be worth it to focus on improving the server performance instead. If you're using a service like CloudFlare you can offload static file handling to the CDN relatively easily.

**Comment by tareco** [comment]
That works almost perfectly, thank you!

I was lamely hacking loadjs.js as per your first suggestion but I wasn't getting anywhere.

This is what I have now:
```javascript
    loadjs.ready('run', function() {
        console.log('starting application');
    });
    var files = ['app1.js', 'app2.js', 'app3.js', 'app4.js'];
    var dones = [];
    for (var i=0; i<files.length; i++) {
        (function(){
            var f = files[i];
            loadFile(f, 5000, function() {
                dones.push(f);
                console.log(f + ' loaded');
                if (dones.length == files.length) loadjs.done('run');
            });
        })();
    }
```
However `loadjs.done('run')` does not seem to be working, can you help?

**Comment by amorey** [comment]
It looks like you're using `loadjs.done()` and `loadjs.ready()` correctly. Are the files `appN.js` actually available? If not, then the server will return a 404 and success callback won't be called.

**Comment by tareco** [comment]
Yes, I double checked, I can see the "loaded" messages in the console, and also the message inside the `if`.

**Comment by amorey** [comment]
Sorry, I forgot that `loadjs.ready()` takes a success/error object as an argument:
```javascript
loadjs.ready('run', {
  success: function() { console.log('starting application'); }
});
```

**Comment by tareco** [comment]
Bullseye! Perfect, thank you so much for this lib and for your patience lecturing me :-)

**Comment by amorey** [comment]
No prob! Let me know if you have any more questions.
