### ISSUE TITLE
Uncaught LoadJS at success

### ISSUE THREAD

**Issue by JFGHT** [muicss/loadjs#53]
I'm using LoadJS with ReactJS.

This code is inside ComponentWillReceiveProps:
https://jsfiddle.net/6n2khubb/

It works perfectly, even the setState executes correctly but the Uncaught LoadJS jumps in anyway.
If  I comment the line

`this.setState({
                                    reducers: reducers
                                })`

then, no exception is shown.

I'm using scriptjs with the same code and works like a charm.

**Comment by amorey** [comment]
That error is thrown when a bundle is defined multiple times so the most likely explanation is your `loadjs` code is being called twice:
https://github.com/muicss/loadjs/blob/master/src/loadjs.js#L197-L204

**Comment by JFGHT** [comment]
True that. Thanks for the fast answer anyway.
