### ISSUE TITLE
Bundle ids in dependency lists are not working

### ISSUE THREAD

**Issue by Craz-z-zy** [muicss/loadjs#61]
Bundle ids in dependency lists are not working (example number 7). 
Bundle id in dependency list detects like a script. In the browser's console it shows as script not loaded (status 500). Loadjs calls error callback.

**Comment by amorey** [comment]
Can you share your code so I can see what the issue is? Here's an example that uses bundle ids in dependency lists:
https://jsfiddle.net/muicss/ts5fv67L/

**Comment by Craz-z-zy** [comment]
https://codepen.io/txid/pen/pLRqYx - copy of code with some changes https://jsfiddle.net/muicss/ts5fv67L/
And this is situation at my local server:
![loadjs](https://user-images.githubusercontent.com/37551693/37653347-2f18889e-2c71-11e8-8522-94c7720b05d5.png)

**Comment by amorey** [comment]
Thanks for sharing your code. I took a closer look at the JSFiddle and it works because JSFiddle doesn't return a `404 Not Found` when you access a file/subdirectory that doesn't exist. As you described, there is an error in the documentation. This is the proper way to express the dependencies in the example:
```javascript
loadjs(['/foo1.js', '/foo2.js'], 'foo');
loadjs('/bar.js', 'bar');

loadjs.ready(['foo', 'bar'], {
  success: function() {alert("foobar");},
  error: function (notFound) {console.log("Not found: " + notFound);}
});
```

I will update the documentation shortly.

**Comment by Craz-z-zy** [comment]
The code base is your's. I have only used browser console to debug code, that doesn't worked. 
Online web developing tools gives different results. But where were not result the same as my.

Thank you.
I have solved my problem the next way:
```javascript
loadjs(['/some_library.js', '/extension_for_some_library.js'], 'some', { async: false });
loadjs(['/my_script.js'], 'mylib');
loadjs.ready(['some', 'mylib'], {
       success: function() { alert("success"); },
       error: function(notFound) { alert("Not found: " + notFound); }
});
```
