### ISSUE TITLE
Support loading scripts with "crossorigin" atrribute

### ISSUE THREAD

**Issue by debopamsengupta** [muicss/loadjs#66]
Hello :) would it be possible to add support for adding a crossorigin property to scripts being loaded using `loadjs` .

This is mainly because if these scripts end up having errors, consumers of such scripts only end up with non-descriptive `Script error.` messages.

I'd be happy to make a PR with this feature.

**Comment by amorey** [comment]
You add a crossorigin property to each script using the `before` callback:

```javascript
loadjs(['/path/to/foo.js', '/path/to/bar.js'], {
  success: function() {},
  error: function(pathsNotFound) {},
  before: function(path, scriptEl) {
    /* called for each script node before being embedded */
    if (path === '/path/to/foo.js') scriptEl.crossOrigin = true;
  }
});
```

(See example 14 here: https://github.com/muicss/loadjs)

**Comment by debopamsengupta** [comment]
awesome thanks :)
