### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by cekvenich** [muicss/loadjs#70]
Version 3.5.4 :

loadjs.js:106 Uncaught TypeError: Cannot read property 'replace' of undefined
    at loadFile (loadjs.js:106)
    at loadFiles (loadjs.js:197)
    at loadjs (loadjs.js:228)

**Comment by amorey** [comment]
Can you describe how to reproduce the error?

**Comment by cekvenich** [comment]
I passed a bad array [ , 'something'].
Maybe a try catch.

Also, seems like events are on capture, not on bubble?

Last, please reconsider adding require. Please. tia.

**Comment by amorey** [comment]
Which events are you referring to?

**Comment by cekvenich** [comment]
'ready' events.
I have so settimeout to 1 to do my work on ready.

**Comment by amorey** [comment]
Can you be more specific? LoadJS doesn't capture or dispatch any DOM events. Are you referring to the `DOMContentLoaded` event (i.e. `$(document).ready()`)?
