### ISSUE TITLE
Bug loading Google Font

### ISSUE THREAD

**Issue by batata004** [muicss/loadjs#74]
When loading Google Font it does not end with *.css so this library does not work cause it tries to interpret the file as JS not at CSS.

`loadjs(["//fonts.googleapis.com/css?family=Montserrat|Raleway:400,700|Abel|Libre+Baskerville:400i","style.css"]);`

The style.css loads fine but the google font does not load correctly and Firefox shows an error at console.

**Comment by amorey** [comment]
You can use a "css!" prefix to force treat a file as a stylesheet:
```javascript
loadjs(["css!//fonts.googleapis.com/css?family=Montserrat|Raleway:400,700|Abel|Libre+Baskerville:400i", "style.css"]);
```

**Comment by batata004** [comment]
A M A Z I N G! It should be on documentation, thanks a lot!

**Comment by amorey** [comment]
No prob! It's "#4" here:
https://github.com/muicss/loadjs#documentation

**Comment by batata004** [comment]
Sorry my mistake! The documentation was very clear about that, I was the curlprit cause I didnt read it all. Thanks for pointing it.
