### ISSUE TITLE
Update comments in src to clarify arguments to loadJs

### ISSUE THREAD

**Issue by asos-tomp** [muicss/loadjs#88]
The sourcecode indicates that a fourth argument to `loadJs` is possible, as `arg[3]`:

https://github.com/muicss/loadjs/blob/master/src/loadjs.js#L216

...however, I'm not sure this is correct, I believe the third argument would be ignored?   I think `arg[2]` could have the comment:
```
 * @param {Function|Object} [arg2] - The success or error callback or object literal with success/error arguments, numRetries, etc.
```
...or something more snappy!

Similarly, as per the example:
```
loadjs(['/path/to/foo.js', '/path/to/bar.js'], {
  success: function() { /* foo.js and bar.js loaded in series */ },
  async: false
});
```
...`arg[1]` can actually be an object literal, and not just `{(string|Function)}` as the comment suggests.

**Comment by amorey** [comment]
Fixed! Thanks for the suggestion.
https://github.com/muicss/loadjs/blob/master/src/loadjs.js#L211-L219
