### ISSUE TITLE
Custom script attributes

### ISSUE THREAD

**Issue by sarneeh** [muicss/loadjs#89]
It's often needed to pass custom attributes to the `script` tag. It would be great if `loadjs` would support such a usecase.

Maybe an `attributes` option would do the work?

**Comment by amorey** [comment]
To add custom attributes you can use the `before` callback:
```javascript
loadjs(['/path/to/foo.js', '/path/to/bar.js'], {
  success: function() {},
  error: function(pathsNotFound) {},
  before: function(path, scriptEl) {
    /* called for each script node before being embedded */
    if (path === '/path/to/foo.js') scriptEl.crossOrigin = true;
  }
});
```

**Comment by sarneeh** [comment]
Oh, didn't think about this :D Thanks!

**Comment by amorey** [comment]
No prob! Happy to help.
