### ISSUE TITLE
Do we really need `setTimeout`?

### ISSUE THREAD

**Issue by revyh** [muicss/loadjs#9]
Why script injection [starts after timeout](https://github.com/muicss/loadjs/blob/e22de36c39a599ea20162a03144be86556334b1a/src/loadjs.js#L155-L163)? It delays downloading of scripts, sometimes significantly. There is almost no delay in Chrome, but in FF and IE9 (that's what I've tested so far) timeout event fired after DOMContentLoaded and thus they have notable lag before starting to download scripts. I tried to delete setTimeut and it removes the lag while the code is still passed all tests.

So, the question is: what for do we use `setTimeout`? Comment says that timeout "fires after window 'load' event", but it's neither the truth or explanation why.

If you need, I can do some deeper investigation on this.

**Comment by amorey** [comment]
The call to `setTimeout` originally came from this line in ded's original script.js:
https://github.com/ded/script.js/blob/master/src/script.js#L49

The intention was to start the download after the DOMContentLoaded event fires but if the behavior is different depending on the browser then we should remove it.

Can you confirm that using `setTimeout` executes code before DOMContentLoaded event fires in Chrome but after in FF and IE9?

**Comment by amorey** [comment]
The call to `setTimeout` has been removed in the latest version (v1.6):
https://github.com/muicss/loadjs/commit/8d76a07a8ada96c47a344238e3d66827590ad0e3

**Comment by revyh** [comment]
Thanks for the quick response! I didn't have enought time to respond you yesterday.
