### ISSUE TITLE
Can not detect image if url has ?=rand123456

### ISSUE THREAD

**Issue by tinamore** [muicss/loadjs#96]
Hi,
Has bug in code loadjs:
if url image has ?=..... then loadjs not detect is image
example:
```
loadjs(['/images/sprite/hsp2_v2.png?vsk=1564236054', '/images/sprite/hsp1.png?vsk=1564236054'], function() {
  /* cache image */
});
```
then browser network will load with javascript not image.
![2019-08-05_10-39-16](https://user-images.githubusercontent.com/2157845/62437445-71330c80-b76d-11e9-8f10-258bff7e702f.jpg)

I think regex to css identifier or Image should be:
```
if (/(^css!|\.css.*$)/.test(path)) {

} else if (/(^img!|\.(png|gif|jpg|svg).*$)/.test(path)) {
```

Thanks

**Comment by amorey** [comment]
This has been fixed in v4.0.0: https://github.com/muicss/loadjs/issues/97. Apologies for the delay.
